Repository ovh-ux/ng-ovh-otrs, pull requests merged in 2019-07, with the labels that each got.

#77 fix: handle "other service" correctly
  src/otrs-popup/otrs-popup.controller.js
Labels: bug

#78 Release v7.1.6
  src/otrs-popup/otrs-popup.controller.js
Labels: release :package:

#88 refactor(otrs-popup): remove draggable and minor improvements
  package.json
  src/otrs-popup/otrs-popup.directive.js
  src/otrs-popup/otrs-popup.html
  src/otrs-popup/otrs-popup.less
  yarn.lock
Labels: enhancement

#89 Release v8.0.0
  package.json
  src/otrs-popup/otrs-popup.directive.js
  src/otrs-popup/otrs-popup.html
  src/otrs-popup/otrs-popup.less
  yarn.lock
Labels: release :package:

#92 fix: remove message about dragging the pop-up
  src/otrs-popup/otrs-popup.html
  src/otrs-popup/translations/Messages_fr_FR.xml
Labels: bug

#93 Release v8.0.1
  src/otrs-popup/otrs-popup.html
  src/otrs-popup/translations/Messages_fr_FR.xml
Labels: release :package:
