Repository ovh-ux/ng-ovh-otrs, pull requests merged in 2019-08, with the labels that each got.

#99 fix(otrs.popup): update copy for US customers
  src/otrs-popup/otrs-popup.constant.js
  src/otrs-popup/otrs-popup.controller.js
  src/otrs-popup/otrs-popup.html
  src/otrs-popup/translations/Messages_cs_CZ.xml
  src/otrs-popup/translations/Messages_de_DE.xml
  src/otrs-popup/translations/Messages_en_ASIA.xml
  src/otrs-popup/translations/Messages_en_AU.xml
  src/otrs-popup/translations/Messages_en_CA.xml
  src/otrs-popup/translations/Messages_en_GB.xml
  src/otrs-popup/translations/Messages_en_SG.xml
  src/otrs-popup/translations/Messages_en_US.xml
  src/otrs-popup/translations/Messages_es_ES.xml
  src/otrs-popup/translations/Messages_es_US.xml
  src/otrs-popup/translations/Messages_fi_FI.xml
  src/otrs-popup/translations/Messages_fr_CA.xml
  src/otrs-popup/translations/Messages_fr_FR.xml
  src/otrs-popup/translations/Messages_it_IT.xml
  src/otrs-popup/translations/Messages_lt_LT.xml
  src/otrs-popup/translations/Messages_nl_NL.xml
  src/otrs-popup/translations/Messages_pl_PL.xml
  src/otrs-popup/translations/Messages_pt_PT.xml
Labels: bug

#100 Release v8.0.2
  src/otrs-popup/otrs-popup.constant.js
  src/otrs-popup/otrs-popup.controller.js
  src/otrs-popup/otrs-popup.html
  src/otrs-popup/translations/Messages_cs_CZ.xml
  src/otrs-popup/translations/Messages_de_DE.xml
  src/otrs-popup/translations/Messages_en_ASIA.xml
  src/otrs-popup/translations/Messages_en_AU.xml
  src/otrs-popup/translations/Messages_en_CA.xml
  src/otrs-popup/translations/Messages_en_GB.xml
  src/otrs-popup/translations/Messages_en_SG.xml
  src/otrs-popup/translations/Messages_en_US.xml
  src/otrs-popup/translations/Messages_es_ES.xml
  src/otrs-popup/translations/Messages_es_US.xml
  src/otrs-popup/translations/Messages_fi_FI.xml
  src/otrs-popup/translations/Messages_fr_CA.xml
  src/otrs-popup/translations/Messages_fr_FR.xml
  src/otrs-popup/translations/Messages_it_IT.xml
  src/otrs-popup/translations/Messages_lt_LT.xml
  src/otrs-popup/translations/Messages_nl_NL.xml
  src/otrs-popup/translations/Messages_pl_PL.xml
  src/otrs-popup/translations/Messages_pt_PT.xml
Labels: bug

#106 build: bump ovh-api-services to v9.0.0
  package.json
Labels: dependencies

#109 fix: add excluded service types for us accounts
  src/otrs-popup/otrs-popup.constant.js
  src/otrs-popup/otrs-popup.controller.js
Labels: bug

#113 fix(popup): add excluded service types for us accounts
  src/otrs-popup/otrs-popup.constant.js
  src/otrs-popup/otrs-popup.controller.js
Labels: bug, quality check: ok

#114 Release v9.0.1
  src/otrs-popup/otrs-popup.constant.js
  src/otrs-popup/otrs-popup.controller.js
Labels: release :package:
