Repository ovh-ux/ng-ovh-otrs, pull requests merged in 2019-06, with the labels that each got.

#52 Feat/performance
  .gitignore
  src/index.js
  src/otrs-popup/otrs-popup.constant.js
  src/otrs-popup/otrs-popup.controller.js
  src/otrs-popup/otrs-popup.html
  src/otrs-popup/translations/Messages_fr_FR.xml
Labels: enhancement

#59 fix(popup): filter service by region
  src/otrs-popup/otrs-popup.constant.js
  src/otrs-popup/otrs-popup.controller.js
Labels: bug

#65 Fix typo
  src/otrs-popup/translations/Messages_cs_CZ.xml
  src/otrs-popup/translations/Messages_de_DE.xml
  src/otrs-popup/translations/Messages_en_ASIA.xml
  src/otrs-popup/translations/Messages_en_AU.xml
  src/otrs-popup/translations/Messages_en_CA.xml
  src/otrs-popup/translations/Messages_en_GB.xml
  src/otrs-popup/translations/Messages_en_SG.xml
  src/otrs-popup/translations/Messages_en_US.xml
  src/otrs-popup/translations/Messages_es_ES.xml
  src/otrs-popup/translations/Messages_es_US.xml
  src/otrs-popup/translations/Messages_fi_FI.xml
  src/otrs-popup/translations/Messages_fr_CA.xml
  src/otrs-popup/translations/Messages_fr_FR.xml
  src/otrs-popup/translations/Messages_it_IT.xml
  src/otrs-popup/translations/Messages_lt_LT.xml
  src/otrs-popup/translations/Messages_nl_NL.xml
  src/otrs-popup/translations/Messages_pl_PL.xml
  src/otrs-popup/translations/Messages_pt_PT.xml
Labels: bug

#68 fix(i18n): retrieve translations
  src/otrs-popup/translations/Messages_cs_CZ.xml
  src/otrs-popup/translations/Messages_de_DE.xml
  src/otrs-popup/translations/Messages_en_ASIA.xml
  src/otrs-popup/translations/Messages_en_AU.xml
  src/otrs-popup/translations/Messages_en_CA.xml
  src/otrs-popup/translations/Messages_en_GB.xml
  src/otrs-popup/translations/Messages_en_SG.xml
  src/otrs-popup/translations/Messages_en_US.xml
  src/otrs-popup/translations/Messages_es_ES.xml
  src/otrs-popup/translations/Messages_es_US.xml
  src/otrs-popup/translations/Messages_fi_FI.xml
  src/otrs-popup/translations/Messages_fr_CA.xml
  src/otrs-popup/translations/Messages_it_IT.xml
  src/otrs-popup/translations/Messages_lt_LT.xml
  src/otrs-popup/translations/Messages_nl_NL.xml
  src/otrs-popup/translations/Messages_pl_PL.xml
  src/otrs-popup/translations/Messages_pt_PT.xml
Labels: bug

#69 Release v7.1.4
  src/otrs-popup/translations/Messages_cs_CZ.xml
  src/otrs-popup/translations/Messages_de_DE.xml
  src/otrs-popup/translations/Messages_en_ASIA.xml
  src/otrs-popup/translations/Messages_en_AU.xml
  src/otrs-popup/translations/Messages_en_CA.xml
  src/otrs-popup/translations/Messages_en_GB.xml
  src/otrs-popup/translations/Messages_en_SG.xml
  src/otrs-popup/translations/Messages_en_US.xml
  src/otrs-popup/translations/Messages_es_ES.xml
  src/otrs-popup/translations/Messages_es_US.xml
  src/otrs-popup/translations/Messages_fi_FI.xml
  src/otrs-popup/translations/Messages_fr_CA.xml
  src/otrs-popup/translations/Messages_it_IT.xml
  src/otrs-popup/translations/Messages_lt_LT.xml
  src/otrs-popup/translations/Messages_nl_NL.xml
  src/otrs-popup/translations/Messages_pl_PL.xml
  src/otrs-popup/translations/Messages_pt_PT.xml
Labels: release :package:

#73 fix(i18n): retrieve translations
  src/otrs-popup/translations/Messages_pt_PT.xml
Labels: bug

#74 Release v7.1.5
  package.json
  src/otrs-popup/translations/Messages_pt_PT.xml
  yarn.lock
Labels: release :package:
